# .github/workflows/coverage.yml
name: Run Tests and Report Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov

      - name: Run tests with coverage
        run: |
          pytest --cov=your_package_name --cov-report=xml

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: 1f3091d7-70a4-431f-8ae7-26541c706b5e
        run: |
          codecov -f coverage.xml
